export type DriverStatus = "CLEAR" | "TIGHT_HOS" | "INELIGIBLE" | "OFF_SHIFT";

export interface Driver {
  id: string;
  name: string;
  initials: string;
  status: DriverStatus;
  hosRemaining: number; // hours
  hoursDrivenToday: number;
  weeklyHoursUsed: number;
  weeklyLimit: number;
  location: string;
  load: string;
  lastUpdated: string;
  cpm: number; // cost per mile
  // map position (percent)
  mapX: number;
  mapY: number;
}

export const drivers: Driver[] = [
  {
    id: "1",
    name: "Marcus Reed",
    initials: "MR",
    status: "CLEAR",
    hosRemaining: 9.2,
    hoursDrivenToday: 1.8,
    weeklyHoursUsed: 38,
    weeklyLimit: 70,
    location: "Phoenix, AZ",
    load: "Available",
    lastUpdated: "2 min ago",
    cpm: 1.62,
    mapX: 22,
    mapY: 55,
  },
  {
    id: "2",
    name: "Sarah Chen",
    initials: "SC",
    status: "CLEAR",
    hosRemaining: 8.5,
    hoursDrivenToday: 2.5,
    weeklyHoursUsed: 41,
    weeklyLimit: 70,
    location: "Tucson, AZ",
    load: "Available",
    lastUpdated: "1 min ago",
    cpm: 1.71,
    mapX: 28,
    mapY: 68,
  },
  {
    id: "3",
    name: "Diego Alvarez",
    initials: "DA",
    status: "CLEAR",
    hosRemaining: 7.8,
    hoursDrivenToday: 3.2,
    weeklyHoursUsed: 44,
    weeklyLimit: 70,
    location: "Flagstaff, AZ",
    load: "Phoenix → Albuquerque",
    lastUpdated: "4 min ago",
    cpm: 1.79,
    mapX: 30,
    mapY: 38,
  },
  {
    id: "4",
    name: "Jamal Foster",
    initials: "JF",
    status: "CLEAR",
    hosRemaining: 6.9,
    hoursDrivenToday: 4.1,
    weeklyHoursUsed: 49,
    weeklyLimit: 70,
    location: "Mesa, AZ",
    load: "Available",
    lastUpdated: "3 min ago",
    cpm: 1.84,
    mapX: 25,
    mapY: 58,
  },
  {
    id: "5",
    name: "Olivia Bennett",
    initials: "OB",
    status: "CLEAR",
    hosRemaining: 8.1,
    hoursDrivenToday: 2.9,
    weeklyHoursUsed: 36,
    weeklyLimit: 70,
    location: "Yuma, AZ",
    load: "Available",
    lastUpdated: "5 min ago",
    cpm: 1.69,
    mapX: 14,
    mapY: 70,
  },
  {
    id: "6",
    name: "Ravi Kapoor",
    initials: "RK",
    status: "CLEAR",
    hosRemaining: 7.2,
    hoursDrivenToday: 3.8,
    weeklyHoursUsed: 47,
    weeklyLimit: 70,
    location: "Prescott, AZ",
    load: "Phoenix → Denver",
    lastUpdated: "6 min ago",
    cpm: 1.74,
    mapX: 24,
    mapY: 45,
  },
  {
    id: "7",
    name: "Emma Walsh",
    initials: "EW",
    status: "CLEAR",
    hosRemaining: 9.5,
    hoursDrivenToday: 1.5,
    weeklyHoursUsed: 32,
    weeklyLimit: 70,
    location: "Tempe, AZ",
    load: "Available",
    lastUpdated: "1 min ago",
    cpm: 1.58,
    mapX: 26,
    mapY: 60,
  },
  {
    id: "8",
    name: "Lisa Park",
    initials: "LP",
    status: "TIGHT_HOS",
    hosRemaining: 4.2,
    hoursDrivenToday: 6.8,
    weeklyHoursUsed: 62,
    weeklyLimit: 70,
    location: "El Paso, TX",
    load: "Phoenix → Houston",
    lastUpdated: "8 min ago",
    cpm: 1.81,
    mapX: 52,
    mapY: 70,
  },
  {
    id: "9",
    name: "Tariq Hassan",
    initials: "TH",
    status: "TIGHT_HOS",
    hosRemaining: 3.6,
    hoursDrivenToday: 7.4,
    weeklyHoursUsed: 58,
    weeklyLimit: 70,
    location: "Las Vegas, NV",
    load: "Phoenix → LA",
    lastUpdated: "12 min ago",
    cpm: 1.92,
    mapX: 12,
    mapY: 40,
  },
  {
    id: "10",
    name: "Dave Kim",
    initials: "DK",
    status: "INELIGIBLE",
    hosRemaining: 1.8,
    hoursDrivenToday: 9.2,
    weeklyHoursUsed: 67,
    weeklyLimit: 70,
    location: "Albuquerque, NM",
    load: "Rest Required",
    lastUpdated: "15 min ago",
    cpm: 2.04,
    mapX: 48,
    mapY: 50,
  },
  {
    id: "11",
    name: "Nina Rodriguez",
    initials: "NR",
    status: "OFF_SHIFT",
    hosRemaining: 11.0,
    hoursDrivenToday: 0,
    weeklyHoursUsed: 28,
    weeklyLimit: 70,
    location: "Chandler, AZ",
    load: "Off Shift",
    lastUpdated: "2 hr ago",
    cpm: 1.66,
    mapX: 27,
    mapY: 62,
  },
];

export const lanePerformance = [
  {
    lane: "Phoenix → Dallas",
    cpm: 1.72,
    trips: 18,
    bestDriver: "Marcus Reed",
    status: "Healthy",
  },
  {
    lane: "Phoenix → LA",
    cpm: 1.94,
    trips: 22,
    bestDriver: "Sarah Chen",
    status: "Watch",
  },
  {
    lane: "Phoenix → Denver",
    cpm: 1.81,
    trips: 12,
    bestDriver: "Ravi Kapoor",
    status: "Healthy",
  },
  {
    lane: "Phoenix → Albuquerque",
    cpm: 2.08,
    trips: 9,
    bestDriver: "Diego Alvarez",
    status: "Underperforming",
  },
];
